### ISSUE TITLE
Tracking: Error and Reporting Alignment

### ISSUE THREAD

**Issue by shellscape** [shellscape/webpack#1]
- [ ] Review existing error messages for verbosity
- [x] `abstract class WebpackError`
- [x] `get id             // hash identifying the error`
- [x] `get/set message`
- [x] `get/set name       // name to identify the file, error category, group, etc. eg. "performance" or "configuration"`
- [x] `get/set lineNumber`
- [x] `get/set column`
- [x] `get/set columnEnd  // some webpack errors contain a column range`
- [x] `get metaData       // object provided to set error-specific data. eg. an asset list`
- [x] `function toString([formatterFn])  // formatterFn can/should be set in the constructor, if needed`
- [x] `toString()` will by default output in the following format: `{lineNumber}:{column} {name}: {message}`
- [x] Enforce by proxying as a warning in v3, and as an error in v4+, that all objects pushed to `compilation.errors` and `compilation.warnings` be an instance of `WebpackError`
- [x] Error if `WebpackError`instance is created without minimum set of options: column, lineNumber, message,  name.
- [x] Warn if a `WebpackError` has a message set longer than a reasonable preset value. (Reference `ESLint` for example, which imposes reasonable error message lengths)
